dist:
  name: otelcol-snowflake
  description: Custom OpenTelemetry Collector with Snowflake receiver
  output_path: ./otelcol-snowflake
  otelcol_version: 0.135.0

receivers:
  - gomod: github.com/npcomplete777/snowflakereceiver/receiver v0.0.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.135.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.135.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.135.0

extensions:
  - gomod: go.opentelemetry.io/collector/extension/zpagesextension v0.135.0

replaces:
  - github.com/npcomplete777/snowflakereceiver/receiver => /home/azureuser/snowflakereceiver/receiver
  - github.com/npcomplete777/snowflakereceiver => /home/azureuser/snowflakereceiver
