# Production Monitoring Configuration
# Balanced 5-minute interval for operational visibility

receivers:
  snowflake:
    # Connection Details
    user: "${SNOWFLAKE_USER}"              # Use environment variables
    password: "${SNOWFLAKE_PASSWORD}"
    account: "myorg-prod123"               # Format: orgname-accountname (lowercase)
    warehouse: "COMPUTE_WH"
    database: "SNOWFLAKE"
    schema: "ACCOUNT_USAGE"
    role: "ACCOUNTADMIN"
    
    # Collection Settings
    collection_intervals:
      historical: "5m"                     # 5 minutes - good balance
    
    # Metric Categories
    metrics:
      query_history: true                  # Query performance details
      credit_usage: true                   # Warehouse credit tracking
      storage_metrics: true                # Account storage usage
      login_history: true                  # Authentication monitoring
      data_pipeline: true                  # Snowpipe activity
      database_storage: true               # Per-database storage

processors:
  batch:
    timeout: 10s
    send_batch_size: 1000

exporters:
  otlphttp:
    endpoint: "${OTLP_ENDPOINT}"
    headers:
      Authorization: "Bearer ${OTLP_TOKEN}"
    timeout: 30s
    retry_on_failure:
      enabled: true
      max_elapsed_time: 300s

service:
  pipelines:
    metrics:
      receivers: [snowflake]
      processors: [batch]
      exporters: [otlphttp]
