# Dynatrace Export Configuration
# Production monitoring with Dynatrace backend

receivers:
  snowflake:
    user: "${SNOWFLAKE_USER}"
    password: "${SNOWFLAKE_PASSWORD}"
    account: "vhrlbph-io32862"
    warehouse: "COMPUTE_WH"
    database: "SNOWFLAKE"
    schema: "ACCOUNT_USAGE"
    
    collection_intervals:
      historical: "5m"
    
    metrics:
      query_history: true
      credit_usage: true
      storage_metrics: true
      login_history: true
      data_pipeline: true
      database_storage: true

processors:
  batch:
    timeout: 10s

exporters:
  otlphttp:
    endpoint: "https://YOUR_TENANT.live.dynatrace.com/api/v2/otlp"
    headers:
      Authorization: "Api-Token ${DYNATRACE_API_TOKEN}"
    timeout: 30s

service:
  pipelines:
    metrics:
      receivers: [snowflake]
      processors: [batch]
      exporters: [otlphttp]
