# ============================================================================
# RECOMMENDED STARTER CONFIG - Use this for production!
# ============================================================================
# This config enables ALL 11 metric categories (300+ metrics) with optimized
# polling intervals. Works out-of-the-box with any Snowflake account.
#
# Performance: ~86K metrics/day with default intervals
# Latency: Real-time (1min) for operations, historical (5-30min) for trends
# ============================================================================

receivers:
  snowflake:
    user: "YOUR_SNOWFLAKE_USER"
    password: "YOUR_SNOWFLAKE_PASSWORD"
    account: "your-account-name"
    warehouse: "COMPUTE_WH"
    database: "SNOWFLAKE"
    schema: "ACCOUNT_USAGE"
    
    metrics:
      # Real-time metrics - poll every 1 minute
      current_queries:
        enabled: true
        interval: "1m"
      
      warehouse_load:
        enabled: true
        interval: "1m"
      
      # Historical metrics with 45min-3hr lag - poll every 5 minutes
      query_history:
        enabled: true
        interval: "5m"
      
      credit_usage:
        enabled: true
        interval: "5m"
      
      # Storage updates daily - poll every 30 minutes
      storage_metrics:
        enabled: true
        interval: "30m"
      
      # Login security - poll every 10 minutes
      login_history:
        enabled: true
        interval: "10m"
      
      # Data pipeline - poll every 10 minutes
      data_pipeline:
        enabled: true
        interval: "10m"
      
      # Database storage updates daily - poll every 30 minutes
      database_storage:
        enabled: true
        interval: "30m"
      
      # Task execution - poll every 10 minutes
      task_history:
        enabled: true
        interval: "10m"
      
      # Replication - poll every 15 minutes
      replication_usage:
        enabled: true
        interval: "15m"
      
      # Auto-clustering - poll every 15 minutes
      auto_clustering_history:
        enabled: true
        interval: "15m"

processors:
  batch:
    timeout: 10s

exporters:
  otlphttp:
    endpoint: "https://YOUR_TENANT.live.dynatrace.com/api/v2/otlp"
    headers:
      Authorization: "Api-Token YOUR_DYNATRACE_API_TOKEN"

service:
  pipelines:
    metrics:
      receivers: [snowflake]
      processors: [batch]
      exporters: [otlphttp]
