receivers:
  snowflake:
    user: "YOUR_SNOWFLAKE_USER"
    password: "YOUR_SNOWFLAKE_PASSWORD"
    account: "your-account-name"
    warehouse: "COMPUTE_WH"
    database: "SNOWFLAKE"
    schema: "ACCOUNT_USAGE"
    collection_interval: "2m"
    
    metrics:
      # Real-time
      current_queries: true
      warehouse_load: true
      # Historical  
      query_history: true
      credit_usage: true
      storage_metrics: true
      login_history: true
      data_pipeline: true
      database_storage: true
      task_history: true
      replication_usage: true
      auto_clustering_history: true

processors:
  batch:
    timeout: 10s

exporters:
  otlphttp:
    endpoint: "https://YOUR_TENANT.live.dynatrace.com/api/v2/otlp"
    headers:
      Authorization: "Api-Token YOUR_DYNATRACE_API_TOKEN"

service:
  pipelines:
    metrics:
      receivers: [snowflake]
      processors: [batch]
      exporters: [otlphttp]
