# Debug Configuration
# Test receiver with detailed console output

receivers:
  snowflake:
    user: "your_username"
    password: "your_password"
    account: "orgname-accountname"
    warehouse: "COMPUTE_WH"
    database: "SNOWFLAKE"
    schema: "ACCOUNT_USAGE"
    
    # Fast polling for testing
    collection_intervals:
      historical: "30s"
    
    # All metrics enabled
    metrics:
      query_history: true
      credit_usage: true
      storage_metrics: true
      login_history: true
      data_pipeline: true
      database_storage: true

processors:
  batch:
    timeout: 10s

exporters:
  debug:
    verbosity: detailed                    # Print all metrics to console

service:
  telemetry:
    logs:
      level: debug                         # Verbose logging
  pipelines:
    metrics:
      receivers: [snowflake]
      processors: [batch]
      exporters: [debug]
