receivers:
  snowflake:
    user: "YOUR_SNOWFLAKE_USER"
    password: "YOUR_SNOWFLAKE_PASSWORD"
    account: "your-account-name"
    warehouse: "COMPUTE_WH"
    database: "SNOWFLAKE"
    schema: "ACCOUNT_USAGE"
    
    # Standard metrics
    metrics:
      current_queries:
        enabled: true
        interval: "1m"
      warehouse_load:
        enabled: true
        interval: "1m"
      query_history:
        enabled: true
        interval: "5m"
      credit_usage:
        enabled: true
        interval: "5m"
      storage_metrics:
        enabled: true
        interval: "30m"
      login_history:
        enabled: false
      data_pipeline:
        enabled: false
      database_storage:
        enabled: false
      task_history:
        enabled: false
      replication_usage:
        enabled: false
      auto_clustering_history:
        enabled: false
    
    # Event tables disabled
    event_tables:
      enabled: false
    
    # ORGANIZATION METRICS - Multi-Account Monitoring! 🌐
    organization:
      enabled: true
      
      org_credit_usage:
        enabled: true
        interval: "1h"  # Hourly org-wide credit tracking
      
      org_storage_usage:
        enabled: true
        interval: "1h"  # Hourly org-wide storage
      
      org_data_transfer:
        enabled: true
        interval: "1h"  # Track cross-account transfers
      
      org_contract_usage:
        enabled: true
        interval: "12h"  # Contract tracking twice daily
    
    # Custom queries disabled
    custom_queries:
      enabled: false

processors:
  batch:
    timeout: 10s

exporters:
  otlphttp:
    endpoint: "https://YOUR_TENANT.live.dynatrace.com/api/v2/otlp"
    headers:
      Authorization: "Api-Token YOUR_DYNATRACE_API_TOKEN"

service:
  pipelines:
    metrics:
      receivers: [snowflake]
      processors: [batch]
      exporters: [otlphttp]
